import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/app/components/Header"
import PageLayout from "@/app/components/PageLayout"
import { getBackgroundImages } from "@/app/actions"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = await getBackgroundImages()
  const images = data.data.allImages
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <PageLayout images={images}>{children}</PageLayout>
      </body>
    </html>
  )
}
