import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "@/app/components/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Header />
        <main
          style={{
            height: "calc(100vh - 70px)",
            display: "flex",
            flexDirection: "column",
            paddingBottom: "2rem",
          }}
        >
          {children}
        </main>
      </body>
    </html>
  )
}
